<#
.SYNOPSIS
    Builds the foo_floating_clouds foobar2000 plugin.

.DESCRIPTION
    - Defaults to Release / x64.
    - Resolves vcvarsall.bat and MSBuild from a Visual Studio install (default
      "D:\APPS\Visual Studio"), then builds the plugin project.
    - -Clean / -CleanOnly remove generated build outputs, strictly scoped to
      this workspace. Everything deleted is printed first; use -WhatIf to preview.
    - Safety: refuses to run as admin, refuses to operate at a drive root, and
      never touches anything outside the workspace.

.PARAMETER Configuration
    Debug or Release (default: Release).

.PARAMETER Platform
    x64 or Win32 (default: x64).

.PARAMETER VsInstallDir
    Visual Studio installation directory (default: D:\APPS\Visual Studio).

.PARAMETER Clean
    Clean build outputs first, then build.

.PARAMETER CleanOnly
    Only clean build outputs, do not build.

.PARAMETER Force
    Skip the interactive confirmation prompt when cleaning.

.PARAMETER Deploy
    Copy the freshly built DLL into a foobar2000 "components" folder
    (requires -Foobar2000Dir).

.PARAMETER Foobar2000Dir
    Root folder of a foobar2000 installation (only used with -Deploy).

.PARAMETER Package
    After a successful build, package the DLL into an installable
    foo_floating_clouds.fb2k-component file under .\dist.

.PARAMETER MinVersion
    Minimum foobar2000 version written into the package manifest
    (default: 2.0).

.EXAMPLE
    .\build.ps1
    .\build.ps1 -Configuration Debug -Platform x64
    .\build.ps1 -Clean -Force
    .\build.ps1 -CleanOnly -WhatIf
    .\build.ps1 -Package
    .\build.ps1 -Deploy -Foobar2000Dir "D:\foobar2000"
#>
[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Low')]
param(
    [ValidateSet('Debug', 'Release')] [string] $Configuration = 'Release',
    [ValidateSet('x64', 'Win32')]      [string] $Platform     = 'x64',
    [string] $VsInstallDir = 'D:\APPS\Visual Studio',
    [switch] $Clean,
    [switch] $CleanOnly,
    [switch] $Force,
    [switch] $Deploy,
    [string] $Foobar2000Dir = '',
    [switch] $Package,
    [string] $MinVersion = '2.0'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# 0. Preflight / safety
# ---------------------------------------------------------------------------

# Refuse to run elevated: not needed for building, and cleaning while elevated
# is riskier than helpful.
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if ($isAdmin) {
    Write-Warning 'Running elevated. Not required; consider running as a normal user.'
}

# Workspace root = folder containing this script.
$WorkspaceRoot = (Resolve-Path $PSScriptRoot).Path
Set-Location $WorkspaceRoot

# Never operate at a drive root (e.g. C:\) — a safety net against catastrophic cleans.
$rootItem = Get-Item $WorkspaceRoot
if ($null -eq $rootItem.Parent) {
    throw "Refusing to operate at a drive root: $WorkspaceRoot"
}

# Resolve vcvarsall.bat from the chosen VS install.
$vcvars = Join-Path $VsInstallDir 'VC\Auxiliary\Build\vcvarsall.bat'
if (-not (Test-Path -LiteralPath $vcvars)) {
    throw "vcvarsall.bat not found at: $vcvars`n  Install VS Build Tools with the C++ workload, or pass -VsInstallDir."
}

# Resolve MSBuild (prefer the one inside the same VS install, else PATH).
$msbuild = Join-Path $VsInstallDir 'MSBuild\Current\Bin\MSBuild.exe'
if (-not (Test-Path -LiteralPath $msbuild)) {
    $found = Get-Command msbuild -ErrorAction SilentlyContinue
    $msbuild = if ($found) { $found.Source } else { '' }
}
if ([string]::IsNullOrWhiteSpace($msbuild) -or -not (Test-Path -LiteralPath $msbuild)) {
    throw 'MSBuild.exe not found. Install VS Build Tools or pass -VsInstallDir.'
}

$ProjectFile = Join-Path $WorkspaceRoot 'foo_floating_clouds\foo_floating_clouds.vcxproj'
if (-not (Test-Path -LiteralPath $ProjectFile)) {
    throw "Project file not found: $ProjectFile"
}

$arch = if ($Platform -eq 'x64') { 'x64' } else { 'x86' }

Write-Host "== Floating Clouds build ==" -ForegroundColor Cyan
Write-Host "  Workspace : $WorkspaceRoot"
Write-Host "  Config    : $Configuration / $Platform"
Write-Host "  VS        : $VsInstallDir"
Write-Host "  MSBuild   : $msbuild"
Write-Host ""

# ---------------------------------------------------------------------------
# 1. Clean
# ---------------------------------------------------------------------------

function Get-BuildOutputDirs {
    param(
        [string] $Root,
        [int]    $MaxDepth = 5
    )
    # Build-output directory names generated by MSBuild for this repo.
    $names = @('x64', 'Win32', 'Debug', 'Release', 'ipch', '.vs')
    $results = [System.Collections.Generic.List[string]]::new()
    $queue = [System.Collections.Generic.Queue[object]]::new()
    $queue.Enqueue([pscustomobject]@{ Path = $Root; Depth = 0 })

    while ($queue.Count -gt 0) {
        $node = $queue.Dequeue()
        if ($node.Depth -gt $MaxDepth) { continue }
        foreach ($d in Get-ChildItem -LiteralPath $node.Path -Directory -Force -ErrorAction SilentlyContinue) {
            if ($d.Name -eq '.git') { continue }            # never touch git metadata
            if ($names -contains $d.Name) {
                $results.Add($d.FullName)                   # collect, do not descend
            } elseif ($node.Depth -lt $MaxDepth) {
                $queue.Enqueue([pscustomobject]@{ Path = $d.FullName; Depth = $node.Depth + 1 })
            }
        }
    }
    return $results
}

function Invoke-Clean {
    # Directory names that can only ever be build outputs (see $names above).
    $dirs = @(Get-BuildOutputDirs -Root $WorkspaceRoot)
    # VS-generated per-user files and stray build logs.
    $userFiles = @(Get-ChildItem -LiteralPath $WorkspaceRoot -Depth 3 -Filter '*.user' -File -Force -ErrorAction SilentlyContinue)
    $logs      = @(Get-ChildItem -LiteralPath $WorkspaceRoot -Depth 1 -Filter 'build_*.txt' -File -Force -ErrorAction SilentlyContinue)

    if ($dirs.Count -eq 0 -and $userFiles.Count -eq 0 -and $logs.Count -eq 0) {
        Write-Host 'Nothing to clean.' -ForegroundColor Yellow
        return
    }

    $summary = 'Will remove {0} build output folder(s), {1} .user file(s), {2} log file(s):' -f `
        $dirs.Count, $userFiles.Count, $logs.Count
    Write-Host $summary -ForegroundColor Cyan
    $dirs  | ForEach-Object { Write-Host ('  [D] ' + $_) }
    $userFiles | ForEach-Object { Write-Host ('  [F] ' + $_.FullName) }
    $logs  | ForEach-Object { Write-Host ('  [F] ' + $_.FullName) }

    # Interactive confirmation unless -Force (or -WhatIf, which is non-destructive).
    if (-not $Force -and -not $WhatIfPreference -and [Environment]::UserInteractive) {
        $ans = Read-Host 'Proceed with the cleanup above? [y/N]'
        if ($ans -notmatch '^[yY]') { Write-Host 'Clean cancelled.' -ForegroundColor Yellow; return }
    }

    foreach ($d in $dirs) {
        if ($PSCmdlet.ShouldProcess($d, 'Remove directory')) {
            Remove-Item -LiteralPath $d -Recurse -Force -ErrorAction Stop
        }
    }
    foreach ($f in $userFiles + $logs) {
        if ($PSCmdlet.ShouldProcess($f.FullName, 'Remove file')) {
            Remove-Item -LiteralPath $f.FullName -Force -ErrorAction Stop
        }
    }
    Write-Host 'Clean finished.' -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# 2. Build
# ---------------------------------------------------------------------------

function Invoke-Build {
    $cmdLine = '"{0}" {1} && "{2}" "{3}" /p:Configuration={4} /p:Platform={5} /p:VisualStudioVersion=17.0 /m' `
        -f $vcvars, $arch, $msbuild, $ProjectFile, $Configuration, $Platform
    Write-Host ">> $cmdLine" -ForegroundColor Cyan

    if ($WhatIfPreference) { return }   # -WhatIf: just show, don't run

    # Run via a temporary .bat file. Passing a command with quoted paths
    # (spaces!) straight to `cmd.exe /c` mangles the quoting, so we avoid it.
    $bat = Join-Path $env:TEMP "build_foo_floating_clouds_$PID.bat"
    try {
        $lineVcvars = 'call "{0}" {1}' -f $vcvars, $arch
        $lineMsbuild = '"{0}" "{1}" /p:Configuration={2} /p:Platform={3} /p:VisualStudioVersion=17.0 /m' -f $msbuild, $ProjectFile, $Configuration, $Platform
        $content = '@echo off' + "`r`n" + $lineVcvars + "`r`n" + 'if errorlevel 1 exit /b %errorlevel%' + "`r`n" + $lineMsbuild + "`r`n" + 'exit /b %errorlevel%'
        Set-Content -LiteralPath $bat -Value $content -Encoding ASCII
        & cmd.exe /d /c "`"$bat`""
        if ($LASTEXITCODE -ne 0) {
            throw "Build FAILED (exit code $LASTEXITCODE)."
        }
    } finally {
        Remove-Item -LiteralPath $bat -Force -ErrorAction SilentlyContinue
    }

    Write-Host "Build succeeded: $Configuration / $Platform" -ForegroundColor Green

    $dll = if ($Platform -eq 'Win32') {
        Join-Path $WorkspaceRoot "foo_floating_clouds\$Configuration\foo_floating_clouds.dll"
    } else {
        Join-Path $WorkspaceRoot "foo_floating_clouds\x64\$Configuration\foo_floating_clouds.dll"
    }
    if (Test-Path -LiteralPath $dll) {
        $len = (Get-Item $dll).Length
        Write-Host ('  Output: {0} ({1:N0} bytes)' -f $dll, $len) -ForegroundColor Green
    }

    if ($Deploy) { Invoke-Deploy -DllPath $dll }
    if ($Package) { New-ComponentPackage -DllPath $dll }
}

# ---------------------------------------------------------------------------
# 3.5 Package (optional) - build a .fb2k-component install file
# ---------------------------------------------------------------------------

function New-ComponentPackage {
    param([string] $DllPath)

    if (-not (Test-Path -LiteralPath $DllPath)) {
        throw "Built DLL not found at: $DllPath"
    }

    $componentName = 'foo_floating_clouds'
    $outDir = Join-Path $WorkspaceRoot 'dist'
    $outZip = Join-Path $outDir "$componentName.fb2k-component"
    $stage  = Join-Path $env:TEMP "fb2k_pkg_$PID"

    if ($WhatIfPreference) {
        Write-Host "Would create: $outZip  (from $DllPath)" -ForegroundColor Cyan
        return
    }

    try {
        if (Test-Path -LiteralPath $stage) { Remove-Item -LiteralPath $stage -Recurse -Force }
        New-Item -ItemType Directory -Path $stage | Out-Null

        # 1) The component DLL (name must start with "foo_").
        Copy-Item -LiteralPath $DllPath -Destination (Join-Path $stage "$componentName.dll") -Force

        # 2) The manifest: a plain-text file with the SAME base name as the
        #    component, placed at the archive root. foobar2000 reads the minimum
        #    version from it and finds the DLL by name.
        $manifest = Join-Path $stage "$componentName.fb2k-component"
        Set-Content -LiteralPath $manifest -Value ('foobar2000 v' + $MinVersion) -Encoding ASCII

        # 3) ZIP the staging contents (entries at archive root, not nested).
        New-Item -ItemType Directory -Path $outDir -Force | Out-Null
        if (Test-Path -LiteralPath $outZip) { Remove-Item -LiteralPath $outZip -Force }
        Add-Type -AssemblyName System.IO.Compression.FileSystem -ErrorAction SilentlyContinue
        [System.IO.Compression.ZipFile]::CreateFromDirectory($stage, $outZip, [System.IO.Compression.CompressionLevel]::Optimal, $false)

        Write-Host "Packaged: $outZip" -ForegroundColor Green
        Write-Host ('  Size    : {0:N0} bytes' -f (Get-Item $outZip).Length) -ForegroundColor Green
        Write-Host '  Contents:' -ForegroundColor Cyan
        $zip = [System.IO.Compression.ZipFile]::OpenRead($outZip)
        try {
            $zip.Entries | ForEach-Object { Write-Host ('    ' + $_.FullName) }
        } finally {
            $zip.Dispose()
        }
        Write-Host 'Install: foobar2000 > File > Preferences > Components > Install...' -ForegroundColor DarkGray
    } finally {
        Remove-Item -LiteralPath $stage -Recurse -Force -ErrorAction SilentlyContinue
    }
}

# ---------------------------------------------------------------------------
# 3. Deploy (optional)
# ---------------------------------------------------------------------------

function Invoke-Deploy {
    param([string] $DllPath)

    if ([string]::IsNullOrWhiteSpace($Foobar2000Dir)) {
        throw '-Deploy requires -Foobar2000Dir <path to a foobar2000 folder>.'
    }
    $components = Join-Path $Foobar2000Dir 'components'
    if (-not (Test-Path -LiteralPath $components)) {
        throw "foobar2000 components folder not found: $components"
    }
    if (-not (Test-Path -LiteralPath $DllPath)) {
        throw "Built DLL not found at: $DllPath"
    }

    $dest = Join-Path $components 'foo_floating_clouds.dll'
    Write-Host "Deploying to $dest" -ForegroundColor Cyan
    if ($PSCmdlet.ShouldProcess($dest, 'Overwrite DLL in components')) {
        try {
            Copy-Item -LiteralPath $DllPath -Destination $dest -Force -ErrorAction Stop
            Write-Host 'Deployed. Restart foobar2000 if it is already running.' -ForegroundColor Green
        } catch {
            Write-Warning ("Could not copy to $dest`n  {0}`n  If foobar2000 is running, close it and retry." -f $_.Exception.Message)
        }
    }
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if ($CleanOnly) {
    Invoke-Clean
    return
}

if ($Clean) {
    Invoke-Clean
}

Invoke-Build
